### ISSUE TITLE
Add search to docs

### ISSUE THREAD

**Issue by maltsev** [posthtml/htmlnano#147]
See https://docusaurus.io/docs/search

**Comment by maltsev** [comment]
For some reason, the build always fails on Netlify with the following error:

```
Error: Generating OpenSearch file failed: TypeError: Url must be a string. Received undefined
1:34:29 PM:     at Object.postBuild (/opt/build/repo/docs/node_modules/@docusaurus/theme-search-algolia/src/index.js:68:15)
1:34:29 PM:     at /opt/build/repo/docs/node_modules/@docusaurus/core/lib/commands/build.js:158:22
1:34:29 PM:     at Array.map (<anonymous>)
1:34:29 PM:     at buildLocale (/opt/build/repo/docs/node_modules/@docusaurus/core/lib/commands/build.js:154:31)
1:34:29 PM:     at async tryToBuildLocale (/opt/build/repo/docs/node_modules/@docusaurus/core/lib/commands/build.js:32:20)
1:34:29 PM:     at async Object.mapAsyncSequencial (/opt/build/repo/docs/node_modules/@docusaurus/utils/lib/index.js:317:24)
1:34:29 PM:     at async build (/opt/build/repo/docs/node_modules/@docusaurus/core/lib/commands/build.js:68:25)
```

I haven't figured yet why it happens. So the search isn't working yet on https://htmlnano.netlify.app/

**Comment by maltsev** [comment]
I managed to fix that issue. The reason behind that was the undefined `favicon` field. So I had to set it to some non-undefined and non-empty value (although, I have no favicon yet).

**Comment by maltsev** [comment]
Now the search isn't working because `contextualSearch: true` is set. Without it, it'd return duplicate results from different versions. I'll contact the support to try to solve that.

**Comment by maltsev** [comment]
Now it works. I just had to wait until Algolia refetches the docs again.
